### ISSUE TITLE
Error generating gamelist xml

### ISSUE THREAD

**Issue by Chinoforest** [pdrb/mamescraper#2]
All the information gets downloaded right but at the time of the gamelist generation it gives me this error:

 zwackery information scrapped
 zwackery.png exists skipping download
 zzyzzyxx information scrapped
 zzyzzyxx.png exists skipping download
Done!

Generating new gamelist xml...
Traceback (most recent call last):
  File "mamescraper.py", line 587, in <module>
  File "mamescraper.py", line 574, in cli
  File "mamescraper.py", line 424, in save_gamelist_xml
  File "xml\etree\ElementTree.py", line 820, in write
  File "xml\etree\ElementTree.py", line 939, in _serialize_xml
  File "xml\etree\ElementTree.py", line 939, in _serialize_xml
  File "xml\etree\ElementTree.py", line 937, in _serialize_xml
  File "xml\etree\ElementTree.py", line 1075, in _escape_cdata
  File "xml\etree\ElementTree.py", line 1052, in _raise_serialization_error
TypeError: cannot serialize 4 (type int)
Failed to execute script mamescraper

**Comment by pdrb** [comment]
Arcade database (adb) changed their api, causing this error.

I just fixed the script to reflect those changes and it is working now.
